name: Bug Report
description: Found 
title: "[Bug] <short description>"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you so much for helping out periodt by reporting a bug! Please fill out the details below :)

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the bug in as much detail as you can, every little big can help us figure out what's wrong quicker.
      placeholder: A clear and concise description of what the bug is.

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the bug?
      placeholder: 1. Go to '...'\n2. Click on '...'\n3. See error

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: input
    id: app_version
    attributes:
      label: App Version
      description: What version of the app are you using? (You can find this at the bottom of the settings page in Periodt.)
      placeholder: e.g. 1.2.3

  - type: input
    id: device
    attributes:
      label: Device & OS
      description: What device and operating system are you using? (If you're not sure what this means for an iPhone try [this](https://support.apple.com/en-us/109065) and for an android try [this](https://support.google.com/android/answer/7680439?hl=en))
      placeholder: e.g. Pixel 5, Android 12

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs/Stacktrace
      description: Paste any relevant logs or stacktrace here if you have them.
      render: shell